name: uaplatform
markdown: redcarpet
pygments: true

encoding: utf-8

comments :
  provider : facebook
  disqus :
    short_name : jekyllbootstrap
  livefyre :
    site_id : 123
  intensedebate :
    account : 123abc
  facebook :
    appid : 123
    num_posts: 5
    width: 580
    colorscheme: light
    
